### ISSUE TITLE
在/_posts/添加markdown文件如何在主页显示出来呢

### ISSUE THREAD

**Issue by Nellyan4** [youdeliang/vuepress-theme-melodydl#4]
您好，我按照config设置好了_posts文件夹，在里面添加了markdown文件之后，请问要做什么配置才能在主页显示出来呢？
谢谢

**Comment by youdeliang** [comment]
这个是主题插件，具体如何配置和如何生成站点，可以参考我自己生成的博客站点项目仓库https://github.com/youdeliang/youdeliang.github.io。依葫芦画瓢，拉下来本地运行，然后数据、图片和文章换成自己的就ok，如果有配置不懂得也可以阅读文档来看具体配置得作用。
